### ISSUE TITLE
Exists() method not accounting for bucket types

### ISSUE THREAD

**Issue by bfitzsimmons** [tpjg/goriakpbc#84]
After converting my code to use the new bucket types my tests for the existence of objects are failing. <MyBucket>.Exists(<ObjectKey>) currently returns `false` no matter what.

**Comment by MJDSys** [comment]
Hey @bfitzsimmons, did PR #85 fix your issue?  If so, can you please close this issue?  Thanks.

**Comment by bfitzsimmons** [comment]
It did fix it.  Thanks, again.
