### ISSUE TITLE
Travis CI randomly fails in search_test.go on line 40

### ISSUE THREAD

**Issue by MJDSys** [tpjg/goriakpbc#89]
As pointed out in PR #88, Travis CI randomly fails in search_test.go on line 40.  Re-running the tests on Travis can remove the error, and it hasn't been reproducible locally.  This needs fixing on Travis, or the test needs work to make it more robust.

**Comment by MJDSys** [comment]
A quick investigation reveals Riak is having issues with the search query.  Logs from a Travis run can be seen here: https://travis-ci.org/MJDSys/goriakpbc/jobs/46886895 .

**Comment by tpjg** [comment]
Interesting logging you've produced. Looks like Riak is going down just by running this simple search query.

**Comment by tpjg** [comment]
Closed by PR #90 .
